config/routes.rb
Rails.application.routes.draw do
  # get 'contact/index'

  devise_for :users
  # get 'about/index'

  root 'home#index'
  
  resources :contact
  resources :about
  resources :home

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/contact/index.html.erb
<h1>Contact#index</h1>
<p>Find me in app/views/contact/index.html.erb</p>

app/views/home/index.html.erb
<!--banner-section-->
		<div class="banner-section">
		   <h3 class="tittle">General <i class="glyphicon glyphicon-picture"></i></h3>
			<div class="banner">
                <div  class="callbacks_container">
					<ul class="rslides" id="slider4">
				       <li>
                            <%= image_tag "1.jpg", class: "img-responsive" %>
						</li>
						<li>
                            <%= image_tag "2.jpg", class: "img-responsive" %>
						</li>
						<li>
						    <%= image_tag "3.jpg", class: "img-responsive" %>
						</li>
						<li>
						     <%= image_tag "3.jpg", class: "img-responsive" %>
						</li>
					</ul>
				</div>
			     
		         <div class="clearfix"> </div>
			     <div class="b-bottom"> 
			          <h5 class="top"><a href="single.html">What turn out consetetur sadipscing elit</a></h5>
			          <p>On Aug 25 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="single.html"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
				 </div>
			 </div>
			   <!--//banner-->
			  <!--/top-news-->
			  <div class="top-news">
				<div class="top-inner">
					<div class="col-md-6 top-text">
						 <a href="single.html">
						     <%= image_tag "pic1.jpg", class: "img-responsive" %>
						 </a>
						    <h5 class="top"><a href="#">Consetetur sadipscing elit</a></h5>
							<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
						    <p>On Jun 25 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
					</div>
					<div class="col-md-6 top-text two">
						 <a href="single.html">
						     <%= image_tag "pic2.jpg", class: "img-responsive" %>
						 </a>
						    <h5 class="top"><a href="#">Consetetur sadipscing elit</a></h5>
							<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
						    <p>On Jun 27 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
					 </div>
					 <div class="clearfix"> </div>
				 </div>
				 <div class="top-inner second">
					<div class="col-md-6 top-text">
						 <a href="single.html">
						     <%= image_tag "pic3.jpg", class: "img-responsive" %>
						 </a>
						    <h5 class="top"><a href="#">Consetetur sadipscing elit</a></h5>
							<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
						    <p>On Jun 25 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
					 </div>
					<div class="col-md-6 top-text two">
						 <a href="single.html">
						     <%= image_tag "pic4.jpg", class: "img-responsive" %>
						 </a>
						    <h5 class="top"><a href="#">Consetetur sadipscing elit</a></h5>
							<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
						    <p>On Jun 27 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
					 </div>
					 <div class="clearfix"> </div>
				 </div>
	            </div>
					<!--//top-news-->
		</div>
		
		<div class="banner-right-text">
			 <h3 class="tittle">News  <i class="glyphicon glyphicon-facetime-video"></i></h3>
			<!--/general-news-->
			 <div class="general-news">
				<div class="general-inner">
					<div class="general-text">
						 <a href="single.html">
						     <%= image_tag "gen1.jpg", class: "img-responsive" %>
						 </a>
						    <h5 class="top"><a href="single.html">Consetetur sadipscing elit</a></h5>
							<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
						    <p>On Jun 25 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="single.html"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
					 </div>
					 <div class="edit-pics">
							      <div class="editor-pics">
										 <div class="col-md-3 item-pic">
										   <%= image_tag "f4.jpg", class: "img-responsive" %>

										   </div>
											<div class="col-md-9 item-details">
												<h5 class="inner two"><a href="single.html">New iPad App to simulate your Guitar</a></h5>
												 <div class="td-post-date two"><i class="glyphicon glyphicon-time"></i>Feb 22, 2015 <a href="#"><i class="glyphicon glyphicon-comment"></i>0 </a></div>
											 </div>
											<div class="clearfix"></div>
										</div>
										<div class="editor-pics">
										 <div class="col-md-3 item-pic">
										    <%= image_tag "f1.jpg", class: "img-responsive" %>

										   </div>
											<div class="col-md-9 item-details">
												<h5 class="inner two"><a href="#">New iPad App to simulate your Guitar</a></h5>
												 <div class="td-post-date two"><i class="glyphicon glyphicon-time"></i>Feb 22, 2015 <a href="#"><i class="glyphicon glyphicon-comment"></i>0 </a></div>
											 </div>
											<div class="clearfix"></div>
										</div>
										<div class="editor-pics">
										 <div class="col-md-3 item-pic">
										   <%= image_tag "f1.jpg", class: "img-responsive" %>

										   </div>
											<div class="col-md-9 item-details">
												<h5 class="inner two"><a href="#">New iPad App to simulate your Guitar</a></h5>
												 <div class="td-post-date two"><i class="glyphicon glyphicon-time"></i>Feb 22, 2015 <a href="#"><i class="glyphicon glyphicon-comment"></i>0 </a></div>
											 </div>
											<div class="clearfix"></div>
										</div>
										<div class="editor-pics">
										 <div class="col-md-3 item-pic">
										   <%= image_tag "f4.jpg", class: "img-responsive" %>

										   </div>
											<div class="col-md-9 item-details">
												<h5 class="inner two"><a href="#">New iPad App to simulate your Guitar</a></h5>
												 <div class="td-post-date two"><i class="glyphicon glyphicon-time"></i>Feb 22, 2015 <a href="#"><i class="glyphicon glyphicon-comment"></i>0 </a></div>
											 </div>
											<div class="clearfix"></div>
										</div>
									</div>
								<div class="media">	
								 <h3 class="tittle media">Media <i class="glyphicon glyphicon-floppy-disk"></i></h3>
								  <div class="general-text two">
									 <a href="single.html">
									     <%= image_tag "gen3.jpg", class: "img-responsive" %>
									 </a>
										<h5 class="top"><a href="#">Consetetur sadipscing elit</a></h5>
										<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
										<p>On Jun 27 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="single.html"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
								  </div>
					         </div>
					    <div class="general-text two">
						    <a href="single.html">
						        <%= image_tag "gen2.jpg", class: "img-responsive" %>
						    </a>
						    <h5 class="top"><a href="#">Consetetur sadipscing elit</a></h5>
							<p>Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt labore dolore magna aliquyam eratsed diam justo duo dolores rebum.</p>
						    <p>On Jun 27 <a class="span_link" href="#"><span class="glyphicon glyphicon-comment"></span>0 </a><a class="span_link" href="#"><span class="glyphicon glyphicon-eye-open"></span>56 </a><a class="span_link" href="single.html"><span class="glyphicon glyphicon-circle-arrow-right"></span></a></p>
					    </div>
				 </div>
			</div>	
		 </div>
			<div class="clearfix"> </div>
		
		<script>
    			    // You can also use "$(window).load(function() {"
    			    $(function () {
    			      // Slideshow 4
    			      $("#slider4").responsiveSlides({
    			        auto: true,
    			        pager:true,
    			        nav:true,
    			        speed: 500,
    			        namespace: "callbacks",
    			        before: function () {
    			          $('.events').append("<li>before event fired.</li>");
    			        },
    			        after: function () {
    			          $('.events').append("<li>after event fired.</li>");
    			        }
    			      });
    			
    			    });
    			      </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},900);
			});
		});
    </script>
  </head>

  <body>
        <div class="h-top" id="home">
		   <div class="top-header">
			  <ul class="cl-effect-16 top-nag">
			      <% if user_signed_in? %>
					<li>
					    <a href="#" data-hover="#">
					        <% if current_user.first_name && current_user.first_name == blank? %>
					            <%= current_user.email %>
					        <% else %>
					            <%= current_user.first_name %> <%= current_user.last_name %>
					        <% end %>
					    </a>
					</li>
					<li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
					<% else %>
					    <li><a href="<%= new_user_registration_path %>" data-hover="Registration">Registration</a></li>
					    <li><a href="<%= new_user_session_path %>" data-hover="Login">Login</a></li>
					<% end %>
					<li><a href="<%= about_index_path %>" data-hover="About">About</a></li>
					<li><a href="#" data-hover="SERVICES">SERVICES</a></li>
					
					<li><a href="<%= contact_index_path %>" data-hover="CONTACT">Contact</a></li>
				</ul>
				<div class="search-box">
			        <div class="b-search">
						<form>
							<input type="text" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
							<input type="submit" value="">
						</form>
					</div>
				</div>

				<div class="clearfix"></div>
			</div>
        </div>
        <div class="full">
            <div class="col-md-3 top-nav">
			     <div class="logo">
					<a href="<%= root_url %>"><h1>Blogger</h1></a>
				</div>
				<div class="top-menu">
					 <span class="menu"> </span>

					<ul class="cl-effect-16">
						<li><a class="active" href="#" data-hover="HOME">Home</a></li> 
						<li><a href="<%= about_index_path %>" data-hover="About">About</a></li>
						<li><a href="#" data-hover="Grids">Grids</a></li>
						<li><a href="#" data-hover="Services">Services</a></li>
						<li><a href="#" data-hover="Gallery">Gallery</a></li>
						<li><a href="<%= contact_index_path %>" data-hover="CONTACT">Contact</a></li>
					</ul>
					<!-- script-for-nav -->
					<script>
						$( "span.menu" ).click(function() {
						  $( ".top-menu ul" ).slideToggle(300, function() {
							// Animation complete.
						  });
						});
					</script>
				    <!-- script-for-nav --> 	
					<ul class="side-icons">
						<li><a class="fb" href="#"></a></li>
						<li><a class="twitt" href="#"></a></li>
						<li><a class="goog" href="#"></a></li>
						<li><a class="drib" href="#"></a></li>
				   </ul>
			    </div>
		    </div>
            <div class="col-md-9 main">
                <p class="notice"><%= notice %></p>
                 <p class="alert"><%= alert %></p>
        
                <%= yield %>
            
                <div class="footer">
    				 <div class="footer-top">
    				    <div class="col-md-4 footer-grid">
    					     <h4>Lorem sadipscing </h4>
    				          <ul class="bottom">
    							 <li>Consetetur sadipscing elitr</li>
    							 <li>Magna aliquyam eratsed diam</li>
    						 </ul>
    				    </div>
					    <div class="col-md-4 footer-grid">
			                <h4>Message Us Now</h4>
			                <ul class="bottom">
					             <li><i class="glyphicon glyphicon-home"></i>Available 24/7 </li>
						         <li><i class="glyphicon glyphicon-envelope"></i><a href="mailto:info@example.com">mail@example.com</a></li>
					       </ul>
				         </div>
    					<div class="col-md-4 footer-grid">
    					     <h4>Address Location</h4>
    				           <ul class="bottom">
    						     <li><i class="glyphicon glyphicon-map-marker"></i>2901 Glassgow Road, WA 98122-1090 </li>
    							 <li><i class="glyphicon glyphicon-earphone"></i>phone: (888) 123-456-7899 </li>
    						   </ul>
    				    </div>
    					<div class="clearfix"> </div>
    				 </div>
    	         </div>
	            <div class="copy">
	                <p>&copy; 2016 Blogger. All Rights Reserved | Design by <a href="http://w3layouts.com/">W3layouts</a> </p>
	            </div>
                 <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>	

        <script type="text/javascript">
			$(document).ready(function() {
				$().UItoTop({ easingType: 'easeOutQuart' });
			});
		</script>
		<a href="#home" id="toTop" class="scroll" style="display: block;"> <span id="toTopHover" style="opacity: 1;"> </span></a>
  </body>
</html>